Humble edits to "Quick Start" section of ENG docs.
drogonframework/drogon-docs pull request #37
Opened 2022-05-25 04:17 UTC by angstyloop

Please review my humble edits to the excellent English documentation
as I work my way through the examples. Dracarys!

2022-05-30 15:13 UTC, an-tao requested changes

2022-05-30 15:13 UTC, an-tao commented on ENG-03-Quick-Start.md
> +The default root path is `"./"`, the project root (not the build directory). This could also be modified by config.json. See [Configuration File](ENG-10-Configuration-File) for more details. Then you
where `./` represents the working directory of the application, if you run your application in the build directory, './' is the build directory.

2022-05-30 15:15 UTC, an-tao commented
@angstyloop Thank you very much and sorry for the delay in replying. It looks fine to me except for the description of the `./` directory.

2022-05-31 06:01 UTC, angstyloop commented on ENG-03-Quick-Start.md
> +The default root path is `"./"`, the project root (not the build directory). This could also be modified by config.json. See [Configuration File](ENG-10-Configuration-File) for more details. Then you
That makes sense, and it totally worked for me when I went through the example. I _wanted_ to make the wording clearer here, but I think I actually made it less clear :3 I'll go fix that.

Thanks An!

2022-05-31 16:31 UTC, angstyloop commented on ENG-03-Quick-Start.md
> +The default root path is `"./"`, the project root (not the build directory). This could also be modified by config.json. See [Configuration File](ENG-10-Configuration-File) for more details. Then you
I added a few new commits, and updated the pull request description. The most recent commit fixes my error you described, and provides a little explanation in the commit message.

Besides the fix, the two commits prior to that are just more tiny grammatical fixes and things, that help to polish the already very shiny documentation.

Please let me know if I made any other errors, and thank you for letting me contribute as I play around with Drogon ^.^

2022-06-01 17:36 UTC, merged